name: Reusable Workflow

on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact name
        required: false
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
